# Generated by Django 3.2.5 on 2021-09-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_pearl_users_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pearl_users',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
