# Generated by Django 3.2.5 on 2021-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_pearl_users_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pearl_users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
