# Generated by Django 3.2.5 on 2021-09-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_pearl_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pearl_users',
            name='dateofbirth',
            field=models.DateField(default=datetime.datetime(2021, 9, 14, 15, 0, 55, 235442)),
        ),
    ]
