# Generated by Django 3.2.5 on 2021-09-14 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_pearl_users_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pearl_users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='pearl_users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pearl_users',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='pearl_users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='pearl_users',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pearl_users',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='pearl_users',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pearl_users',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
