# Generated by Django 3.2.5 on 2021-09-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210914_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pearl_users',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
    ]
