# Generated by Django 3.2.5 on 2021-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_dateofbirth_pearl_users_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.AlterField(
            model_name='pearl_users',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
