# Generated by Django 3.2.5 on 2021-09-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210915_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_storage',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_ram',
            field=models.BooleanField(default='False'),
        ),
    ]
