# Generated by Django 3.2.5 on 2021-09-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210923_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home')], max_length=20),
        ),
    ]
