# Generated by Django 4.0 on 2022-04-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_myproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='myproduct',
            unique_together={('product_name', 'slug')},
        ),
    ]
