# Generated by Django 4.0 on 2022-04-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_myproduct_thumbnail_alter_myproduct_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shop.pearl_users')),
            ],
        ),
        migrations.CreateModel(
            name='myProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shop.mycart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myproduct', to='shop.myproduct')),
            ],
        ),
    ]
