# Generated by Django 4.0 on 2022-04-15 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_mycart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
