# Generated by Django 4.0 on 2022-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_mycart_timestamp_mycart_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='user',
        ),
        migrations.AddField(
            model_name='mycart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shop.myProduct'),
        ),
    ]
