# Generated by Django 4.0 on 2022-04-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_mycart_products_mycart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shop.pearl_users'),
        ),
    ]
