# Generated by Django 4.0 on 2022-04-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_mycart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myproduct', to='shop.myproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='myProductCart',
        ),
        migrations.AddField(
            model_name='mycart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='shop.myCartItem'),
        ),
    ]
