# Generated by Django 4.0 on 2022-04-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_mycartitem_delete_myproductcart_mycart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='myVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='products',
        ),
        migrations.AddField(
            model_name='mycartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shop.mycart'),
        ),
    ]
