# Generated by Django 4.0 on 2022-04-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_myvariance_remove_mycart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycartitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_cart', to='shop.mycart'),
        ),
    ]
