# Generated by Django 4.0 on 2022-04-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_mycartitem_notes_alter_mycartitem_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myVariance',
        ),
    ]
