# Generated by Django 4.0 on 2022-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_myvariance'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='size', max_length=25),
        ),
    ]
