# Generated by Django 4.0 on 2022-04-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_myproduct_category_alter_myvariance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('package', 'package'), ('size', 'size'), ('color', 'color')], default='size', max_length=25),
        ),
        migrations.CreateModel(
            name='myProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mycategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.myproduct')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mycategoryvariant')),
            ],
        ),
    ]
