# Generated by Django 4.0 on 2022-04-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_myvariance_category_myproductvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('package', 'package'), ('size', 'size')], default='size', max_length=25),
        ),
    ]
