# Generated by Django 4.0 on 2022-04-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_myproduct_category_alter_myvariance_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproductvariant',
            name='category',
        ),
    ]
