# Generated by Django 4.0 on 2022-04-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210924_0041'),
        ('shop', '0036_remove_car_brand_remove_fleet_car_and_more'),
    ]

    operations = [
    ]
