# Generated by Django 4.0 on 2022-04-25 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_merge_20220424_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='shop.myproduct'),
        ),
        migrations.AlterField(
            model_name='myproductvariant',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myproductvariantvalue',
            name='variant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_value', to='shop.myproductvariant'),
        ),
        migrations.AlterField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('package', 'package'), ('size', 'size')], default='size', max_length=25),
        ),
    ]
