# Generated by Django 4.0 on 2022-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_myproductvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('package', 'package'), ('color', 'color')], default='size', max_length=25),
        ),
    ]
