# Generated by Django 4.0 on 2022-05-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_myvariance_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
                ('color_image', models.ImageField(upload_to='')),
                ('show_only_image', models.BooleanField(default=False)),
                ('show_only_name', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='myproduct',
            name='has_colour_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myvariance',
            name='category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('package', 'package')], default='size', max_length=25),
        ),
        migrations.CreateModel(
            name='myProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.myproduct')),
            ],
        ),
        migrations.CreateModel(
            name='myProductColorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product_color_images', to='shop.myproductcolor')),
            ],
        ),
        migrations.AddField(
            model_name='myproductcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product_color', to='shop.myproduct'),
        ),
    ]
