# Generated by Django 4.0 on 2022-05-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_cart_category_categoryvariant_product_productcolor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVarintValue',
            new_name='ProductVariantValue',
        ),
    ]
