# Generated by Django 4.0 on 2022-05-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_rename_productvarintvalue_productvariantvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ManyToManyField(blank=True, null=True, to='shop.ProductVariantValue'),
        ),
        migrations.CreateModel(
            name='CartItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_variant', to='shop.cartitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_variant_value', to='shop.productvariantvalue')),
            ],
        ),
    ]
