# Generated by Django 4.0 on 2022-05-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_cartitemvariant_item_cartitemcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
