# Generated by Django 4.0 on 2022-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_remove_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemvariant',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
