# Generated by Django 4.0 on 2022-05-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_cartitemvariant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemvariant',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitemvariant',
            name='variant',
        ),
        migrations.DeleteModel(
            name='CartItemColor',
        ),
        migrations.DeleteModel(
            name='CartItemVariant',
        ),
    ]
