# Generated by Django 4.0 on 2022-05-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_cartitemvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemVariant',
        ),
    ]
