# Generated by Django 4.0 on 2022-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_delete_cartitemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vari', models.CharField(max_length=10)),
                ('demo', models.CharField(max_length=10)),
            ],
        ),
    ]
