# Generated by Django 4.0 on 2022-05-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_cartitemvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItemVariant',
        ),
    ]
