# Generated by Django 4.0 on 2022-05-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_delete_cartitemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_variant', to='shop.cartitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_variant_value', to='shop.productvariantvalue')),
            ],
        ),
    ]
