# Generated by Django 4.0 on 2022-05-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_cartitemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_color_value', to='shop.productcolor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_color', to='shop.cartitem')),
            ],
        ),
    ]
